### ISSUE TITLE
Dependency Inversion

### ISSUE THREAD

**Issue by maksgir** [zinchenko291/ITMO_PROG_LAB3#3]
https://github.com/zinchenko291/ITMO_PROG_LAB3/blob/6668aca69bbf9817ac18cea15282bd8fab027719/src/Items/Container.java#L18

вот эта проверка на instance станет ненужной если поставить тип параметра IGrabbable.

**Comment by zinchenko291** [comment]
Исправил в коммите [12ac0e7](https://github.com/zinchenko291/ITMO_PROG_LAB3/commit/12ac0e70a721fcc3394eb1a6fc3ada10fddc4c1b)

https://github.com/zinchenko291/ITMO_PROG_LAB3/blob/12ac0e70a721fcc3394eb1a6fc3ada10fddc4c1b/src/Items/Container.java#L16-L19
