### ISSUE TITLE
лишний свитч 

### ISSUE THREAD

**Issue by maksgir** [zinchenko291/ITMO_PROG_LAB3#4]
https://github.com/zinchenko291/ITMO_PROG_LAB3/blob/6668aca69bbf9817ac18cea15282bd8fab027719/src/Characters/Character.java#L25

если вдруг станет 100500 гендеров однажды, метод возрастется на сотни тысяч строк.  enums могут хранить переменные и даже методы, покажите это здесь

**Comment by zinchenko291** [comment]
Исправил в коммите [12ac0e7](https://github.com/zinchenko291/ITMO_PROG_LAB3/commit/12ac0e70a721fcc3394eb1a6fc3ada10fddc4c1b)

https://github.com/zinchenko291/ITMO_PROG_LAB3/blob/12ac0e70a721fcc3394eb1a6fc3ada10fddc4c1b/src/Characters/Gender.java#L3-L17
