### ISSUE TITLE
Поля у enum#2

### ISSUE THREAD

**Issue by maksgir** [zinchenko291/ITMO_PROG_LAB3#5]
https://github.com/zinchenko291/ITMO_PROG_LAB3/blob/6668aca69bbf9817ac18cea15282bd8fab027719/src/Characters/FrenBok.java#L14
тут то же самое

**Comment by zinchenko291** [comment]
Исправил в коммите [6463f53](https://github.com/zinchenko291/ITMO_PROG_LAB3/commit/6463f53f0d31b80b4e3c768d0e74aa8b84a8d4d6)

https://github.com/zinchenko291/ITMO_PROG_LAB3/blob/6463f53f0d31b80b4e3c768d0e74aa8b84a8d4d6/src/Characters/Feels.java#L3-L20
