### ISSUE TITLE
DI #2 

### ISSUE THREAD

**Issue by maksgir** [zinchenko291/ITMO_PROG_LAB3#6]
https://github.com/zinchenko291/ITMO_PROG_LAB3/blob/6668aca69bbf9817ac18cea15282bd8fab027719/src/Characters/FrenBok.java#L41

по логике , можно л=толкать только character'a - почему бы не сделать параметр таким типом , и не нужно будет никаких лишних проверок

**Comment by zinchenko291** [comment]
Исправил в коммите [12ac0e7](https://github.com/zinchenko291/ITMO_PROG_LAB3/commit/12ac0e70a721fcc3394eb1a6fc3ada10fddc4c1b)

https://github.com/zinchenko291/ITMO_PROG_LAB3/blob/12ac0e70a721fcc3394eb1a6fc3ada10fddc4c1b/src/Characters/FrenBok.java#L41-L46
